title: Lekcje JavaScript
description: Kurs JS publikowany z Jekyll na GitHub Pages
theme: minima
plugins:
  - jekyll-feed

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: page

collections:
    pages:
        output: true
        permalink: /:path/

